version: "3.8"
services:
  api:
    image: nicoc12024/zone_clocker:api-tag 
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=zone_clocker
    ports:
      - "8800:8800"
    depends_on:
      - db
  client:
    image: nicoc12024/zone_clocker:client-tag 
    ports:
      - "3000:3000"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zone_clocker
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
